@startuml




skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 10

skinparam BoxPadding 10

autonumber


actor User as User


box "view" #lightBlue
participant "ViewComponent" as ViewComponent

end box


box "controller" #LightGoldenRodYellow

participant "AdminController" as AdminJS
end box

box "resources" #lightBlue

participant AdminResource as AdminResource
participant DoctorResource as DoctorResource
participant PatientResource as PatientResource
participant NewsResource as NewsResource
participant NewsCategoryResource as NewsCategoryResource
participant EcgRecordsResource as EcgRecordsResource
participant PatientDoctorAssignmentResource as PatientDoctorAssignmentResource

end box

opt  Authentication success

opt CRUD action on DoctorResource

User -> ViewComponent: Performs CRUD action on DoctorResource  
activate User
activate ViewComponent
ViewComponent -> AdminJS: Send request to performs CRUD action
activate AdminJS
AdminJS -> DoctorResource: Processes CRUD action on DoctorResource
activate DoctorResource
DoctorResource --> AdminJS: Returns CRUD action result
deactivate DoctorResource
AdminJS --> ViewComponent :Return result
deactivate AdminJS
ViewComponent --> User: Display result
deactivate ViewComponent
deactivate User
end

opt CRUD action on AdminResource

User -> ViewComponent: Performs CRUD action on AdminResource  
activate User
activate ViewComponent
ViewComponent -> AdminJS: Send request to performs CRUD action
activate AdminJS
AdminJS -> AdminResource: Processes CRUD action on AdminResource
activate AdminResource
AdminResource --> AdminJS: Returns CRUD action result
deactivate AdminResource
AdminJS --> ViewComponent :Return result
deactivate AdminJS
ViewComponent --> User: Display result
deactivate ViewComponent
deactivate User
end

opt CRUD action on PatientResource

User -> ViewComponent: Performs CRUD action on PatientResource  
activate User
activate ViewComponent
ViewComponent -> AdminJS: Send request to performs CRUD action
activate AdminJS
AdminJS -> PatientResource: Processes CRUD action on PatientResource
activate PatientResource
PatientResource --> AdminJS: Returns CRUD action result
deactivate PatientResource
AdminJS --> ViewComponent :Return result
deactivate AdminJS
ViewComponent --> User: Display result
deactivate ViewComponent
deactivate User
end

opt CRUD action on NewsResource

User -> ViewComponent: Performs CRUD action on NewsResource  
activate User
activate ViewComponent
ViewComponent -> AdminJS: Send request to performs CRUD action
activate AdminJS
AdminJS -> NewsResource: Processes CRUD action on NewsResource
activate NewsResource
NewsResource --> AdminJS: Returns CRUD action result
deactivate NewsResource
AdminJS --> ViewComponent :Return result
deactivate AdminJS
ViewComponent --> User: Display result
deactivate ViewComponent
deactivate User
end

opt CRUD action on NewsCategoryResource

User -> ViewComponent: Performs CRUD action on NewsCategoryResource  
activate User
activate ViewComponent
ViewComponent -> AdminJS: Send request to performs CRUD action
activate AdminJS
AdminJS -> NewsCategoryResource: Processes CRUD action on NewsCategoryResource
activate NewsCategoryResource
NewsCategoryResource --> AdminJS: Returns CRUD action result
deactivate NewsCategoryResource
AdminJS --> ViewComponent :Return result
deactivate AdminJS
ViewComponent --> User: Display result
deactivate ViewComponent
deactivate User
end

opt CRUD action on EcgRecordsResource

User -> ViewComponent: Performs CRUD action on EcgRecordsResource  
activate User
activate ViewComponent
ViewComponent -> AdminJS: Send request to performs CRUD action
activate AdminJS
AdminJS -> EcgRecordsResource: Processes CRUD action on EcgRecordsResource
activate EcgRecordsResource
EcgRecordsResource --> AdminJS: Returns CRUD action result
deactivate EcgRecordsResource
AdminJS --> ViewComponent :Return result
deactivate AdminJS
ViewComponent --> User: Display result
deactivate ViewComponent
deactivate User
end

opt CRUD action on PatientDoctorAssignmentResource

User -> ViewComponent: Performs CRUD action on PatientDoctorAssignmentResource  
activate User
activate ViewComponent
ViewComponent -> AdminJS: Send request to performs CRUD action
activate AdminJS
AdminJS -> PatientDoctorAssignmentResource: Processes CRUD action on PatientDoctorAssignmentResource
activate PatientDoctorAssignmentResource
PatientDoctorAssignmentResource --> AdminJS: Returns CRUD action result
deactivate PatientDoctorAssignmentResource
AdminJS --> ViewComponent :Return result
deactivate AdminJS
ViewComponent --> User: Display result
deactivate ViewComponent
deactivate User
end

end

@enduml
