@startuml




skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 10

skinparam BoxPadding 10

autonumber


actor User as User


box "view" #lightBlue
participant "ViewComponent" as ViewComponent

end box


box "controller" #LightGoldenRodYellow

participant "AdminController" as AdminJS
end box

box "resources" #lightBlue

participant AdminResource as AdminResource
participant DoctorResource as DoctorResource
participant PatientResource as PatientResource
participant NewsResource as NewsResource
participant NewsCategoryResource as NewsCategoryResource
participant EcgRecordsResource as EcgRecordsResource
participant PatientDoctorAssignmentResource as PatientDoctorAssignmentResource

end box

User -> ViewComponent: Request to access the admin dashboard
activate User
activate ViewComponent
' alt Authentication
  ' AdminJS -> User: Requests login credentials
  ViewComponent -> AdminJS: Provides login credentials
  activate AdminJS
  AdminJS -> AdminResource: Authenticate(email, password)
  activate AdminResource
  AdminResource --> AdminJS: Returns authentication result
  deactivate AdminResource
' end

alt Authentication success
  ' User -> AdminJS: Successfully authenticated
  AdminJS -> AdminJS: Builds the admin dashboard
  AdminJS -> DoctorResource: Requests data for DoctorResource
  activate DoctorResource
  DoctorResource --> AdminJS: Returns data for DoctorResource
  deactivate DoctorResource
  AdminJS -> AdminResource: Requests data for AdminResource
  activate AdminResource
  AdminResource --> AdminJS: Returns data for AdminResource
  deactivate AdminResource
  AdminJS -> PatientResource: Requests data for PatientResource
  activate PatientResource
  PatientResource --> AdminJS: Returns data for PatientResource
  deactivate PatientResource
  AdminJS -> NewsResource: Requests data for NewsResource
  activate NewsResource
  NewsResource --> AdminJS: Returns data for NewsResource
  deactivate NewsResource
  AdminJS -> NewsCategoryResource: Requests data for NewsCategoryResource
  activate NewsCategoryResource
  NewsCategoryResource --> AdminJS: Returns data for NewsCategoryResource
  deactivate NewsCategoryResource
  AdminJS -> EcgRecordsResource: Requests data for EcgRecordsResource
  activate EcgRecordsResource
  EcgRecordsResource --> AdminJS: Returns data for EcgRecordsResource
  deactivate EcgRecordsResource
  AdminJS -> PatientDoctorAssignmentResource: Requests data for PatientDoctorAssignmentResource
  activate PatientDoctorAssignmentResource
  PatientDoctorAssignmentResource --> AdminJS: Returns data for PatientDoctorAssignmentResource
  deactivate PatientDoctorAssignmentResource

  AdminJS --> ViewComponent: Redirect to /admin

  ViewComponent --> User: Display dashboard page

  else Authentication fail

  AdminJS --> ViewComponent: Redirect to /admin/login
  deactivate AdminJS
  ViewComponent --> User: Display login page
  deactivate ViewComponent
deactivate User

end

@enduml
