'

@startuml


skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 70

skinparam BoxPadding 10

autonumber

actor User as User


participant main as main


box "route" #lightBlue

participant ECGRecordRoute as ECGRecordRoute

end box


box "controller" #LightGoldenRodYellow
participant ECGRecordController as ECGRecordController

end box


box "model" #lightBlue
participant ECGRecordModel as ECGRecordModel

end box


User -> main: Request upload ECG data to server when finish measuring
activate User
activate main

main -> ECGRecordRoute: POST api/ecg-records/upload
activate ECGRecordRoute
note right of main #Aqua
  * Request param:
  Content type: application/form-data
  Request content:
  - file: File
  - user_id: Interger
  - device_id: Interger
  - start_time: Data
  - stop_time: Date
  - sensor_type: String
end note


ECGRecordRoute -> ECGRecordController: uploadEcgData(req, res)
activate ECGRecordController

note right of ECGRecordRoute #Aqua
  * Request param:
  { user_id, device_id, start_time,
  stop_time, sensor_type } = req.body
  filename = req.file
end note

ECGRecordController -> ECGRecordController: Create folder to store ECG data file
ECGRecordController -> ECGRecordController: Store ECG data

ECGRecordController -> ECGRecordModel: create()
note right of ECGRecordController #Aqua
  * Request param
  user_id: req.user_id
  device_id: req.device_id
  data_directory: 
    "upload/record-data/{:device_id}/
    {:user_id-timestamp}/{:filename}"
  start_time: req.start_time
  stop_time: req.stop_time
  sensor_type: rq.sensor_type
end note

activate ECGRecordModel

ECGRecordModel --> ECGRecordController: return 

deactivate ECGRecordModel

ECGRecordController --> ECGRecordRoute: return response

deactivate ECGRecordController

alt response error
  ECGRecordRoute --> main: return exception
  note right of main
    status: "error"
    message: error description
  end note
else response success
  ECGRecordRoute --> main: return response
  deactivate ECGRecordRoute

  note right of main
    status: "success"
    data : ECGRecordModel
  end note
end
main --> User: return response
deactivate main
deactivate User

@enduml

