'

@startuml


skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 70

skinparam BoxPadding 10

autonumber

actor User as User


participant main as main


box "route" #lightBlue

participant PatientDoctorAssignmentRoute as PatientDoctorAssignmentRoute

end box


box "controller" #LightGoldenRodYellow
participant PatientDoctorAssignmentController as PatientDoctorAssignmentController

end box


box "model" #lightBlue
participant PatientDoctorAssignmentModel as PatientDoctorAssignmentModel
participant UserModel as UserModel

end box


User -> main: Request to get doctor information being assign to patient
activate User
activate main

main -> PatientDoctorAssignmentRoute: GET api/patient/{:patientId}/doctor
activate PatientDoctorAssignmentRoute


PatientDoctorAssignmentRoute -> PatientDoctorAssignmentController: getDoctorByPatient(req, res)
activate PatientDoctorAssignmentController

note right of PatientDoctorAssignmentRoute #Aqua
  * Request param:
   - patient_id: patientId
end note

PatientDoctorAssignmentController -> PatientDoctorAssignmentModel: findOne(patientId)

activate PatientDoctorAssignmentModel

PatientDoctorAssignmentModel --> PatientDoctorAssignmentController: return doctor_id

deactivate PatientDoctorAssignmentModel

opt doctor does not exist
PatientDoctorAssignmentController --> PatientDoctorAssignmentRoute: return error

end

PatientDoctorAssignmentController -> UserModel: findOne(doctor_id)
activate UserModel
UserModel --> PatientDoctorAssignmentController: return doctor infomation
deactivate UserModel

PatientDoctorAssignmentController --> PatientDoctorAssignmentRoute: return response

deactivate PatientDoctorAssignmentController

alt response error
  PatientDoctorAssignmentRoute --> main: return exception
  note right of main
    status: "error"
    message: error description
  end note
else response success
  PatientDoctorAssignmentRoute --> main: return response
  deactivate PatientDoctorAssignmentRoute

  note right of main
    status: "success"
    data : doctor information
  end note
end
main --> User: return response
deactivate main
deactivate User

@enduml

