'

@startuml


skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 70

skinparam BoxPadding 10

autonumber

actor User as User


participant main as main


box "route" #lightBlue

participant NewsRoute as NewsRoute

end box


box "controller" #LightGoldenRodYellow
participant NewsController as NewsController

end box


box "model" #lightBlue
participant NewsModel as NewsModel

end box


User -> main: Request to get news contents
activate User
activate main

main -> NewsRoute: GET api/news/{:newsId}
activate NewsRoute


NewsRoute -> NewsController: getNewsById(req, res)
activate NewsController

note right of NewsRoute #Aqua
  * Request param:
   - newsId = req.param
end note

NewsController -> NewsModel: findByPk(newsId)

activate NewsModel

NewsModel --> NewsController: return news

deactivate NewsModel

opt news does not exist
NewsController --> NewsRoute: return error

end


NewsController --> NewsRoute: return response

deactivate NewsController

alt response error
  NewsRoute --> main: return exception
  note right of main
    status: "error"
    message: error description
  end note
else response success
  NewsRoute --> main: return response
  deactivate NewsRoute

  note right of main
    status: "success"
    data : news content
  end note
end
main --> User: return response
deactivate main
deactivate User

@enduml

