@startuml


skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 80

skinparam BoxPadding 10

autonumber

actor User as User


participant main as main


box "route" #lightBlue

participant UserRoute as UserRoute

end box


box "controller" #LightGoldenRodYellow
participant UserController as UserController

end box


box "model" #lightBlue
participant UserModel as UserModel

end box


User -> main: Request to get user infomation by id
activate User
activate main

main -> UserRoute: GET api/users/{:userId}
activate UserRoute


UserRoute -> UserController: getUserById(req, res)
activate UserController

note right of UserRoute #Aqua
* Request param:
userId = req.body.userId
end note


UserController -> UserModel: findByPk(userId)

activate  UserModel

UserModel --> UserController: return user

deactivate UserModel

opt user does not exist
  UserController --> UserRoute: return response error
end



UserController --> UserRoute: return response

deactivate UserController

UserRoute --> main: return response

deactivate UserRoute

main --> User: return response

deactivate main
deactivate User


@enduml


