@startuml

' Define class

package "Controllers" {
    class AuthController
    class ECGRecordController
    class NewsController
    class PatientDoctorAssignmentController
    class UserController
    class AdminController
}

package "Models" {
    class ECGRecordModel
    class NewsModel
    class NewsCategoryModel
    class ResetTokenModel
    class UserModel
    class DeviceModel
    class SessionModel
    class PatientDoctorAssignmentModel
}

package "Routes" {
    class AuthRoute
    class ECGRecordRoute
    class NewsRoute
    class PatientDoctorAssignmentRoute
    class UserRoute
    class AdminRoute
}

package "lib" {
    class Model <<Sequelize>>

}

' Define relationship between classes


' ---------------------AlginLaylout----------------------
' ---Models
UserModel -[hidden]-> PatientDoctorAssignmentModel
SessionModel -[hidden]-> ResetTokenModel
' ECGRecordModel -[hidden]-> DeviceModel
' NewsCategoryModel -[hidden]-> NewsModel
PatientDoctorAssignmentModel -[hidden]-> ECGRecordModel
ResetTokenModel -[hidden]-> NewsCategoryModel


' ---Controller
UserController -[hidden]-> AuthController
' UserController -[hidden]-> ECGRecordController
UserController -[hidden]-> NewsController
AuthController -[hidden]-> ECGRecordController

' -----Route
' ECGRecordRoute -[hidden]-> NewsRoute
ECGRecordRoute -[hidden]-> AuthRoute
ECGRecordRoute -[hidden]-> PatientDoctorAssignmentRoute
PatientDoctorAssignmentRoute -[hidden]-> NewsRoute


' --------------------------------------------------------



' ---------------Controller-----------------------

AuthController *--- UserModel
AuthController *-- ResetTokenModel
AuthController *-- SessionModel



NewsController *--- NewsCategoryModel
NewsController *--- NewsModel

UserController *--- UserModel

PatientDoctorAssignmentController *--- UserModel
PatientDoctorAssignmentController *--- PatientDoctorAssignmentModel

ECGRecordController *--- ECGRecordModel
ECGRecordController *--- PatientDoctorAssignmentModel
ECGRecordController *--- DeviceModel





' ----------------------------------------------------



' ---------------------------Route----------------------

AuthRoute *--- AuthController
ECGRecordRoute *--- ECGRecordController
UserRoute *--- UserController
NewsRoute *--- NewsController
PatientDoctorAssignmentRoute *--- PatientDoctorAssignmentController
AdminRoute *--- AdminController

' --------------------------------------------------------

Model <|--u- Models

@enduml

