@startuml

autonumber
actor ":User" as User
boundary ":View Change Information" as ClientApp
control ":Control Change Information" as Control
entity ":Entity User" as Entity

activate User
User -> ClientApp: Open change information view
activate ClientApp
ClientApp -> ClientApp: Show change information view
ClientApp --> User
User -> ClientApp: Submit information need changing
ClientApp -> Control: Send information need changing
activate Control
Control -> Entity: Save information into database
activate Entity
Entity --> Control: Response a result
deactivate Entity
Control --> ClientApp: Response a result
deactivate Control
ClientApp --> User: Notify response to user
deactivate ClientApp

skinparam style strictuml
@enduml
