@startuml

autonumber
actor ":User" as User
boundary ":View Change password" as ClientApp
control ":Control Change password" as Control
entity ":Entity User" as Entity

activate User
User -> ClientApp: Open change password view
activate ClientApp
ClientApp -> ClientApp: Show change password view
ClientApp --> User
User -> ClientApp: Submit new password (with confirm password)
ClientApp -> Control: Send new password (with confirm password)
activate Control
alt password and confirm password match
  Control -> Entity: Save new password encrypted into database
  activate Entity
  Entity --> Control: Response a result
  deactivate Entity
  Control --> ClientApp: Response a result
  ClientApp --> User: Notify response to user
else password and confirm password do not match 

  Control --> ClientApp: Show error
  deactivate Control

  ClientApp --> User: Require user to submit correct password again
  deactivate ClientApp
end

skinparam style strictuml
@enduml
