
@startuml


skinparam style strictuml

' skinparam lifelineStrategy solid

' skinparam ParticipantPadding 20

' skinparam BoxPadding 10

autonumber

actor User as User



participant ECGController as ECGController
participant BluetoothController as BluetoothController

participant ECGDevice as ECGDevice

activate User
User -> BluetoothController: Turn on Bluetooth
activate BluetoothController
BluetoothController --> User: Turn on succesfully
User -> BluetoothController: Find ECG Device
BluetoothController --> User: Show list devices found
User -> BluetoothController: Choose connect to ECG Device

BluetoothController -> ECGDevice: Request connection with specific Service and Characteristic
note right of BluetoothController #Yellow
* UUID
UUID Service: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
UUID Characteristic: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
end note
activate ECGDevice
ECGDevice --> BluetoothController: Return response connection
BluetoothController --> User: Show response, navigate to MeasurementScreen

User -> BluetoothController: Click button to measure ECG
BluetoothController -> ECGDevice: Request subscribing Characteristic to ECG Device
ECGDevice --> BluetoothController: Return streaming packet
BluetoothController --> ECGController: Send packet to handle data
activate ECGController
ECGController --> User: Process data to show on chart

@enduml
