
@startuml


skinparam style strictuml

' skinparam lifelineStrategy solid

' skinparam ParticipantPadding 20

' skinparam BoxPadding 10

autonumber

actor User as User


' box "controller" #LightGoldenRodYellow
participant AuthProvider as AuthProvider
' end box


' box "storage" #lightBlue
participant LocalStorage as LocalStorage
' end box

activate User
User -> AuthProvider: Open mobile app
activate AuthProvider
AuthProvider -> LocalStorage: Get login user information
activate LocalStorage

alt Login user information existed
LocalStorage --> AuthProvider: Return having information in local storage
AuthProvider --> User: Navigate to HomeScreen

else Login user information not existed
LocalStorage --> AuthProvider: Return no information
AuthProvider --> User: Show login view

User -> AuthProvider: Submit email, password
AuthProvider -> AuthProvider: Validate with data on server

  alt Data existed
  AuthProvider -> LocalStorage: Save data login
  LocalStorage --> AuthProvider: Save succesfully
  deactivate LocalStorage
  AuthProvider --> User: Navigate to HomeScreen
  else Data not existed
  AuthProvider --> User: Submit correct email, password again
  deactivate AuthProvider
  end

end

@enduml
