@startuml

autonumber
actor ":User" as User
boundary ":View Measure ECG" as ClientApp
control ":Control Measure ECG" as Control
entity ":Entity ECG Data" as Entity

activate User
User -> ClientApp: Click button to stop measuring
activate ClientApp
ClientApp -> Control: Send request stop measuring
activate Control
Control -> Entity: Save ECG data (file) measured to server
activate Entity
Entity --> Control: Send response result
deactivate Entity
Control -> ClientApp: Send response result
deactivate Control
ClientApp --> User: Notify result for user
deactivate ClientApp

skinparam style strictuml
@enduml