@startuml

actor ":User" as User
boundary ":View Forgot password" as ClientApp
control ":Control Forgot password" as Control
entity ":Entity User" as Entity
autonumber

activate User
User -> ClientApp: Click button forgot password
activate ClientApp
ClientApp -> ClientApp: Show forgot password view
ClientApp --> User
User -> ClientApp: Submit email to send verification code
ClientApp -> Control: Send email and request forgot password
activate Control
Control -> Entity: Query to check information
activate Entity
Entity --> Control: Return response
Control --> User: Send reset password numbers to user's email
User -> ClientApp: Type numbers in email with new password
ClientApp -> Control: Send numbers and new password

alt Correct reset password numbers 
  Control -> Entity: Save new password to database
  Entity --> Control: Return response
  deactivate Entity
  Control --> ClientApp: Show change password successfully 
  ClientApp --> User: Notify successfully and navigate to login screen
else Incorrect reset password numbers 
  Control --> ClientApp: Show incorrect reset password numbers
  deactivate Control
  ClientApp --> User: Notify user to type numbers again
  deactivate ClientApp
end


skinparam style strictuml
@enduml
