@startuml

actor ":User" as User
boundary ":View Login" as ClientApp
control ":Control Login" as Control
entity ":Entity User" as Entity
autonumber

activate User
User -> ClientApp: Open app
activate ClientApp
ClientApp -> ClientApp: Show login view
User -> ClientApp: Submit login information (email, password)
ClientApp -> ClientApp: Validate login format
alt Format accepted
  ClientApp -> Control: Send login request with information
  activate Control
  Control -> Entity: Query database
  activate Entity
  Entity --> Control: Send response result
  deactivate Entity
  alt Response success
    Control --> ClientApp: Show login successfully
    ClientApp --> User: Notify to user login successfully
  else Response fail
    Control --> ClientApp: Show login fail
    deactivate Control
    ClientApp --> User: Notify to user login fail
  end

else Format rejected
  ClientApp -> User: Require user to submit again
  deactivate ClientApp
end
deactivate User
skinparam style strictuml

@enduml
