@startuml

autonumber
actor ":User" as User
boundary ":View Measure ECG" as ClientApp
control ":Control Measure ECG" as Control

activate User
User -> ClientApp: Click button to start measuring
activate ClientApp
ClientApp -> Control: Start listening data sent from ECG Device
activate Control
Control --> ClientApp: Send response data handled continously
deactivate Control
ClientApp --> User: Show data in chart for user
deactivate ClientApp

skinparam style strictuml

@enduml