@startuml

autonumber
actor ":User" as User
boundary ":View State bluetooth" as ClientApp
control ":Control State bluetooth" as Control
' entity ":Entity Hardware" as Entity

activate User
User -> ClientApp: Click to open view state bluetooth
activate ClientApp
ClientApp -> ClientApp: Show view state bluetooth
ClientApp --> User
alt Bluetooth is turn off state
  User -> ClientApp: Click turn on bluetooth
  ClientApp -> Control: Request turn on bluetooth
  activate Control
  Control --> ClientApp: Response state turn on
  deactivate Control
  ClientApp --> User: Notify and navigate to Find Device screen
else Bluetooth is turn on state
  User -> ClientApp: Click turn off bluetooth
  ClientApp -> Control: Request turn off bluetooth
  activate Control
  Control --> ClientApp: Response state turn off
  deactivate Control
  ClientApp --> User: Show state turn off to user
  deactivate ClientApp
end
skinparam style strictuml

@enduml
